resources:
  - name: code
    type: git
    source:
      uri: https://github.com/chrisumbel/ConcourseIntegration.git
      branch: master
  - name: chrisumbel-docker-image
    type: docker-image
    source:
      repository: {{chrisumbel-docker-image-repository}}
      username: {{chrisumbel-docker-image-username}}
      password: {{chrisumbel-docker-image-password}}

jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
    - task: compile
      privileged: true
      file: code/pipeline/compile.yml
    - task: test
      privileged: true
      file: code/pipeline/test.yml
  - name: integration
    plan:
    - get: code
      passed: [build]
      trigger: true
    - task: docker-compose 
      file: code/pipeline/integrate.yml
      privileged: true
  - name: deploy
    plan:
    - get: code
      passed: [integration]
      trigger: true         
    - put: chrisumbel-docker-image
      params: 
        build: code
